### ISSUE TITLE
values in setup.db

### ISSUE THREAD

**Issue by jab42** [andreoidb64/uebbi#5]
hi,
where can i find the rigtht way/file to permanently change values in the /root/setup_data/setup.db?
tia
jay

**Comment by andreoidb64** [comment]
Hi Jay,
The file is managed by several processes. This means that some of its records are on RAM and will flushed to the disk by those processes; you cannot change the file while the process is active because the process will write its own image to the storage.
Generally speaking, most of entries should be managed by the process itself, not edited by the user.
What do you want to change?
Regards,
Andrea

**Comment by jab42** [comment]
hi andrea,
thanks for the fast reply.
i want to change some values like network.interface to eth0, wireless.set_type to static, the wireless ip, or the ntp servers, and experiment with the other values.
i already tried to stop all python scripts and then change the values in the setup.db.
then they will not be overwritten after the next minute.
but after a reboot, the old values are back.
so they have to be stored elsewhere and then be reconstructed on reboot.
so i need to know where, or what the exact boot procedure is,
or what boot script ist constructing the setup.db file (read and insert serial number and so on).
there already has to be a point where the user configured changes (radio favorites i.e.) are stored permanently...
thanks for any hint.
jay

**Comment by andreoidb64** [comment]
Dear Jay,

Before to modify uebbi settings you should stop all processes related to application.
I suggest you to read this article -> https://github.com/andreoidb64/uebbi/wiki/Debug-e-compilazione (sorry it's italian, ask Google to translate :) )

In brief, you should do:
```
# killall python2.5
# killall msd
# killall fbserver

```
This is the simple part of the job, because the static settings comes from various places and it's not easy to find them.
For instance, eth0 MAC address and S/N are written on read only mounted partition /dev/mtdblock4 or the wifi password is written to totally unexpected place (you should expect something like /etc/wpa_supplicant/wpa_supplicant.conf, not /root/.profile where no one who has minimum of linux knowledge would use such path to store wifi password ! ).

Thankfully, most of the code is linux script or .pyc Python files and you can easily get the .py source code (search for python decompile pyc to py) to find the information you need.

Hope this helped you, let me know if you get any progress for webby :)

Have a nice day,
Andrea

**Comment by Slaw69** [comment]
Hello  ,
are you able to help me with Webby - after changing the software from German to Webby 2.2. The display goes dark and you cannot see the time, the screen brightness adjustment ends at the 3rd level and the screen is black; (

**Comment by Slaw69** [comment]
https://user-images.githubusercontent.com/102926874/161449147-02502f36-4395-4ded-b1c3-6e4a1f10ffac.mp4

**Comment by andreoidb64** [comment]
Hi Jab42,
No, I never seen seen this behavior and the issue is not present on my device.
Try to reflash the firmware and, if still persists, try to test the page http://192.168.1.123/cgi-bin/display-ctrl? (replace "192.168.1.123" with the IP addr of your Uebbi) to set night/day display brightness time.

![image](https://user-images.githubusercontent.com/17703890/163055874-d61d0498-cae8-4423-8ee4-6f9931afadf0.png)

Note: The CGI web page runs the system command: 
`/bin/backlight_test 1`
to set the lowest display brightness.

Sincerely,
andreoidb64
